export const menu = [
    {
        id: 1,
        category: "Club Sandwich",
        products: [
            {
                id: 101,
                name: "Club Sandwich",
                ingredients: [
                    "Pane",
                    "Formaggio",
                    "Uovo",
                    "Pancetta",
                    "Prosciutto",
                    "Insalata",
                    "Pomodoro",
                ],
                price: 8.0,
            },
            {
                id: 102,
                name: "Club Vegetariano",
                ingredients: ["Pane", "Formaggio", "Verdure alla griglia"],
                price: 8.0,
            },
            {
                id: 103,
                name: "Club Kokodè",
                ingredients: [
                    "Pane",
                    "Formaggio",
                    "Insalata",
                    "Pomodoro",
                    "Prosciutto",
                    "Salsa di pollo",
                ],
                price: 8.0,
            },
            {
                id: 104,
                name: "Club Milano",
                ingredients: [
                    "Pane",
                    "Formaggio",
                    "Uovo",
                    "Pancetta",
                    "Insalata",
                    "Pomodoro",
                    "Cotoletta",
                ],
                price: 8.5,
            },
            { id: 105, name: "Club Burger", ingredients: [], price: 9.0 },
            {
                id: 106,
                name: "Club Sandwich",
                ingredients: [
                    "Pane",
                    "Formaggio",
                    "Uovo",
                    "Pancetta",
                    "Hamburger",
                    "Pomodoro",
                    "Insalata",
                ],
                price: 8.0,
            },
        ],
    },
    {
        id: 2,
        category: "Piadine",
        products: [
            {
                id: 201,
                name: "Crudo e Mozzarella",
                ingredients: [],
                price: 6.0,
            },
            {
                id: 202,
                name: "Cotto e Mozzarella",
                ingredients: [],
                price: 6.0,
            },
            { id: 203, name: "Speck e Brie", ingredients: [], price: 6.0 },
            {
                id: 204,
                name: "Mozzarella, Bresaola, Rucola e Grana",
                ingredients: [],
                price: 6.0,
            },
        ],
    },
    {
        id: 3,
        category: "Stuzzicare",
        products: [
            { id: 301, name: "Patatine Dippers", ingredients: [], price: 4.0 },
            { id: 302, name: "Patatine Fritte", ingredients: [], price: 3.5 },
            { id: 303, name: "Olive Ascolane", ingredients: [], price: 4.0 },
            { id: 304, name: "Mozzarelline", ingredients: [], price: 4.0 },
            {
                id: 305,
                name: "Crocchette di Pollo",
                ingredients: [],
                price: 4.0,
            },
        ],
    },
    {
        id: 4,
        category: "Piatti Vari",
        products: [
            {
                id: 401,
                name: "Caprese di Bufala",
                ingredients: ["Pomodoro", "Mozzarella di Bufala"],
                price: 8.5,
            },
            {
                id: 402,
                name: "Carpaccio Rucola e Grana",
                ingredients: ["Carpaccio con rucola e scaglie di grana"],
                price: 9.5,
            },
            {
                id: 403,
                name: "Prosciutto Crudo con Burrata",
                ingredients: [],
                price: 10.0,
            },
            {
                id: 404,
                name: "Prosciutto Crudo con Bufala",
                ingredients: [],
                price: 10.0,
            },
            {
                id: 405,
                name: "Prosciutto Crudo con Melone",
                ingredients: [],
                price: 10.0,
            },
        ],
    },
    {
        id: 5,
        category: "Dessert",
        products: [
            {
                id: 501,
                name: "Tiramisù Classico o Tiramisù Amaretto",
                ingredients: [],
                price: 4.0,
            },
            { id: 502, name: "Dolce Polenta", ingredients: [], price: 4.0 },
            {
                id: 503,
                name: "Salame al Cioccolato",
                ingredients: [],
                price: 4.0,
            },
            { id: 504, name: "Meringata", ingredients: [], price: 4.0 },
            { id: 505, name: "Profiteroles", ingredients: [], price: 4.0 },
            { id: 506, name: "Torta della Nonna", ingredients: [], price: 4.0 },
            {
                id: 507,
                name: "Semifreddo ai Frutti di Bosco / Amaretti",
                ingredients: [],
                price: 4.0,
            },
            {
                id: 508,
                name: "Tartufo Nero o Bianco",
                ingredients: [],
                price: 4.0,
            },
            {
                id: 509,
                name: "Sgroppino al Limone",
                ingredients: [],
                price: 3.0,
            },
        ],
    },
    {
        id: 6,
        category: "Bibite",
        products: [
            {
                id: 601,
                name: "Pepsi alla Spina Piccola",
                ingredients: [],
                price: 2.5,
            },
            { id: 602, name: "Acqua cl. 0,50", ingredients: [], price: 1.5 },
            {
                id: 603,
                name: "Bibite in Barattolo",
                ingredients: [],
                price: 2.5,
            },
            { id: 604, name: "Media cl. 0,75", ingredients: [], price: 2.5 },
        ],
    },
    {
        id: 7,
        category: "Birre alla Spina",
        products: [
            { id: 701, name: "VIP Pils Piccola", ingredients: [], price: 2.5 },
            {
                id: 702,
                name: "Forst Kronen Bionda Piccola",
                ingredients: [],
                price: 2.5,
            },
            {
                id: 703,
                name: "Forst Sixtus Rossa Piccola",
                ingredients: [],
                price: 3.0,
            },
            {
                id: 704,
                name: "Weiben Weihenstephan cl. 0,3",
                ingredients: [],
                price: 3.5,
            },
            {
                id: 705,
                name: "Felsenkeller non filtrata cl. 0,3",
                ingredients: [],
                price: 3.5,
            },
            { id: 706, name: "VIP Pils Media", ingredients: [], price: 4.5 },
            {
                id: 707,
                name: "Forst Kronen Bionda Media",
                ingredients: [],
                price: 4.5,
            },
            {
                id: 708,
                name: "Forst Sixtus Rossa Media",
                ingredients: [],
                price: 5.0,
            },
            { id: 709, name: "VIP Pils Grande", ingredients: [], price: 4.5 },
            {
                id: 710,
                name: "Forst Kronen Bionda Media",
                ingredients: [],
                price: 5.0,
            },
        ],
    },
    {
        id: 8,
        category: "Birre in Bottiglia",
        products: [
            { id: 801, name: "Waizen", ingredients: [], price: 4.5 },
            { id: 802, name: "Birra Artigianale", ingredients: [], price: 4.5 },
        ],
    },
    {
        id: 9,
        category: "Vini Bianco alla Spina",
        products: [
            { id: 901, name: "Frizzante 1/4 Lt", ingredients: [], price: 3.5 },
            { id: 902, name: "Frizzante 1/2 Lt", ingredients: [], price: 6.0 },
            { id: 903, name: "Frizzante 1 Litro", ingredients: [], price: 9.0 },
        ],
    },
    {
        id: 10,
        category: "Vini Rosso",
        products: [
            { id: 1001, name: "Cabernet 1/4 Lt", ingredients: [], price: 4.0 },
            { id: 1002, name: "Cabernet 1/2 Lt", ingredients: [], price: 7.5 },
            {
                id: 1003,
                name: "Cabernet Bottiglia",
                ingredients: [],
                price: 11.0,
            },
            { id: 1004, name: "Raboso 1/4 Lt", ingredients: [], price: 4.0 },
            { id: 1005, name: "Raboso 1/2 Lt", ingredients: [], price: 7.5 },
            {
                id: 1006,
                name: "Raboso Bottiglia",
                ingredients: [],
                price: 11.0,
            },
        ],
    },
    {
        id: 11,
        category: "Vini in Bottiglia",
        products: [
            {
                id: 1101,
                name: "Prosecco Valdobiadene D.O.C.",
                ingredients: [],
                price: 17.0,
            },
            {
                id: 1102,
                name: "Rosso Cabernet Franc",
                ingredients: [],
                price: 11.0,
            },
            {
                id: 1103,
                name: "Bianco Lison D.O.C.G.",
                ingredients: [],
                price: 11.0,
            },
            {
                id: 1104,
                name: "Bianco Chardonnay",
                ingredients: [],
                price: 11.0,
            },
        ],
    },
    {
        id: 12,
        category: "Amari e Liquori",
        products: [
            { id: 1201, name: "Caffè Espresso", ingredients: [], price: 1.2 },
            {
                id: 1202,
                name: "Caffè Decaffeinato",
                ingredients: [],
                price: 1.2,
            },
            { id: 1203, name: "Caffè d'Orzo", ingredients: [], price: 1.2 },
            { id: 1204, name: "Caffè Corretto", ingredients: [], price: 1.5 },
            { id: 1205, name: "Amari e Liquori", ingredients: [], price: 3.0 },
            {
                id: 1206,
                name: "Limoncello / Liquirizia",
                ingredients: [],
                price: 2.5,
            },
            { id: 1207, name: "Grappa Prime Uve", ingredients: [], price: 3.5 },
            { id: 1208, name: "Grappa Barricata", ingredients: [], price: 3.5 },
        ],
    },
    {
        id: 13,
        category: "Pizze Classiche",
        products: [
            {
                id: 1301,
                name: "Marinara",
                ingredients: ["Pomodoro", "Aglio"],
                price: 4.5,
            },
            {
                id: 1302,
                name: "Margherita",
                ingredients: ["Pomodoro", "Mozzarella"],
                price: 4.9,
            },
            {
                id: 1303,
                name: "Romana",
                ingredients: ["Pomodoro", "Mozzarella", "Acciughe"],
                price: 6.0,
            },
            {
                id: 1304,
                name: "Siciliana",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Acciughe",
                    "Olive",
                    "Capperi",
                ],
                price: 7.0,
            },
            {
                id: 1305,
                name: "Prosciutto",
                ingredients: ["Pomodoro", "Mozzarella", "Prosciutto"],
                price: 6.0,
            },
            {
                id: 1306,
                name: "Funghi",
                ingredients: ["Pomodoro", "Mozzarella", "Funghi"],
                price: 6.0,
            },
            {
                id: 1307,
                name: "Viennese",
                ingredients: ["Pomodoro", "Mozzarella", "Würstel"],
                price: 6.0,
            },
            {
                id: 1308,
                name: "Diavola",
                ingredients: ["Pomodoro", "Mozzarella", "Salamino piccante"],
                price: 6.5,
            },
            {
                id: 1309,
                name: "Prosciutto e Funghi",
                ingredients: ["Pomodoro", "Mozzarella", "Prosciutto", "Funghi"],
                price: 7.0,
            },
            {
                id: 1310,
                name: "Parmigiana",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Melanzane",
                    "Parmigiano",
                ],
                price: 7.0,
            },
            {
                id: 1311,
                name: "Peperoni",
                ingredients: ["Pomodoro", "Mozzarella", "Peperoni"],
                price: 6.0,
            },
            {
                id: 1312,
                name: "Tonno e Cipolla",
                ingredients: ["Pomodoro", "Mozzarella", "Tonno", "Cipolla"],
                price: 7.0,
            },
            {
                id: 1313,
                name: "4 Stagioni",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Prosciutto",
                    "Funghi",
                    "Salamino",
                    "Carciofini",
                ],
                price: 8.0,
            },
            {
                id: 1314,
                name: "Capricciosa",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Prosciutto",
                    "Funghi",
                    "Carciofini",
                ],
                price: 7.5,
            },
            {
                id: 1315,
                name: "Calzone",
                ingredients: ["Pomodoro", "Mozzarella", "Prosciutto", "Funghi"],
                price: 7.5,
            },
            {
                id: 1316,
                name: "Pizza della Casa",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Salamino",
                    "Cipolla",
                    "Speck",
                    "Peperoni",
                ],
                price: 8.5,
            },
            {
                id: 1317,
                name: "Pescatora",
                ingredients: ["Pomodoro", "Mozzarella", "Frutti di mare"],
                price: 8.5,
            },
            {
                id: 1318,
                name: "San Daniele",
                ingredients: ["Pomodoro", "Mozzarella", "Prosciutto crudo"],
                price: 7.5,
            },
            {
                id: 1319,
                name: "Ricotta e Spinaci",
                ingredients: ["Pomodoro", "Mozzarella", "Ricotta", "Spinaci"],
                price: 7.5,
            },
            {
                id: 1320,
                name: "Gamberetti",
                ingredients: ["Pomodoro", "Mozzarella", "Gamberetti"],
                price: 8.0,
            },
            {
                id: 1321,
                name: "Brie e Pomodoro Fresco",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Brie",
                    "Pomodoro fresco",
                ],
                price: 7.0,
            },
            {
                id: 1322,
                name: "Gorgonzola e Speck",
                ingredients: ["Pomodoro", "Mozzarella", "Gorgonzola", "Speck"],
                price: 8.0,
            },
            {
                id: 1323,
                name: "Valtellinese",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Bresaola",
                    "Rucola",
                    "Grana",
                ],
                price: 8.0,
            },
            {
                id: 1324,
                name: "Verdure",
                ingredients: ["Pomodoro", "Mozzarella", "Verdure grigliate"],
                price: 7.5,
            },
            {
                id: 1325,
                name: "Diabolica",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Salamino",
                    "Acciughe",
                    "Gorgonzola",
                    "Pomodori secchi",
                ],
                price: 8.0,
            },
            {
                id: 1326,
                name: "Contadina",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Salsiccia",
                    "Würstel",
                    "Cipolla",
                ],
                price: 8.0,
            },
            {
                id: 1327,
                name: "Friarielli e Salsiccia",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Friarielli",
                    "Salsiccia",
                ],
                price: 7.5,
            },
            {
                id: 1328,
                name: "Saporita",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Pomodorini marinati",
                    "Tonno",
                ],
                price: 8.0,
            },
            {
                id: 1329,
                name: "Estate",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Pomodoro fresco",
                    "Basilico",
                ],
                price: 6.0,
            },
            { id: 1330, name: "Tonno", ingredients: [], price: 6.5 },
            { id: 1331, name: "Hawaii", ingredients: [], price: 7.0 },
        ],
    },
    {
        id: 14,
        category: "Pizze Speciali",
        products: [
            {
                id: 1401,
                name: "Golosa",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Porcini",
                    "Gorgonzola",
                    "Speck",
                ],
                price: 8.5,
            },
            {
                id: 1402,
                name: "Kokode",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Pancetta",
                    "Uovo",
                    "Grana",
                    "Salamino",
                ],
                price: 8.5,
            },
            {
                id: 1403,
                name: "Gamberetti e Rucola",
                ingredients: ["Pomodoro", "Mozzarella", "Gamberetti", "Rucola"],
                price: 8.5,
            },
            {
                id: 1404,
                name: "Campagnola",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Zucchine",
                    "Mais",
                    "Pancetta",
                    "Uovo",
                ],
                price: 8.0,
            },
            {
                id: 1405,
                name: "Bufala",
                ingredients: ["Pomodoro", "Mozzarella di bufala", "Basilico"],
                price: 7.5,
            },
            {
                id: 1406,
                name: "Autunno",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Sopressa",
                    "Misto funghi",
                ],
                price: 8.0,
            },
            {
                id: 1407,
                name: "Affumicata",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Misto bosco",
                    "Scamorza affumicata",
                ],
                price: 8.0,
            },
            {
                id: 1408,
                name: "Greca",
                ingredients: [
                    "Pomodoro",
                    "Feta greca",
                    "Formaggio alle erbe",
                    "Olive nere",
                ],
                price: 8.0,
            },
            {
                id: 1409,
                name: "Sfiziosa",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella di bufala",
                    "Acciughe",
                    "Basilico",
                    "Pomodoro fresco",
                ],
                price: 8.0,
            },
            {
                id: 1410,
                name: "Porchettara",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Porchetta",
                    "Peperoni",
                ],
                price: 8.0,
            },
            {
                id: 1411,
                name: "Cavallina",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Sfilacci di cavallo",
                    "Pomodoro fresco",
                ],
                price: 8.0,
            },
            { id: 1412, name: "Americana", ingredients: [], price: 8.0 },
            {
                id: 1413,
                name: "Rusticana",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Pancetta",
                    "Grana a scaglie",
                ],
                price: 8.5,
            },
            {
                id: 1414,
                name: "Sottobosco",
                ingredients: ["Pomodoro", "Mozzarella", "Funghi misti"],
                price: 7.0,
            },
            {
                id: 1415,
                name: "Regina",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Rucola",
                    "Carpaccio",
                    "Funghi crudi",
                    "Scaglie di grana",
                    "Olio tartufato",
                ],
                price: 10.0,
            },
            {
                id: 1416,
                name: "Radicchio di Treviso",
                ingredients: ["Pomodoro", "Mozzarella", "Radicchio di Treviso"],
                price: 6.5,
            },
            { id: 1417, name: "Trevisana N° 1", ingredients: [], price: 8.0 },
            {
                id: 1418,
                name: "Trevisana N° 2",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Radicchio",
                    "Prosciutto alla brace",
                    "Grana",
                ],
                price: 8.7,
            },
            {
                id: 1419,
                name: "Trevisana N° 3",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Radicchio",
                    "Salamino",
                ],
                price: 8.0,
            },
            {
                id: 1420,
                name: "Champignose N° 1",
                ingredients: [
                    "Pomodoro",
                    "Mozzarella",
                    "Funghi crudi",
                    "Rucola",
                    "Grana",
                ],
                price: 8.7,
            },
            { id: 1421, name: "Champignose N° 2", ingredients: [], price: 8.7 },
        ],
    },
    {
        id: 15,
        category: "Pizze Imbufalite",
        products: [
            {
                id: 1501,
                name: "Burrata 1",
                ingredients: [
                    "Pomodoro",
                    "Burrata",
                    "Salamino",
                    "Pomodorini conditi",
                ],
                price: 8.5,
            },
            {
                id: 1502,
                name: "Burrata 2",
                ingredients: [
                    "Pomodoro",
                    "Burrata",
                    "Rucola",
                    "Pomodorini conditi",
                    "Prosciutto crudo",
                ],
                price: 9.5,
            },
            {
                id: 1503,
                name: "Florida",
                ingredients: ["Pomodoro", "Bufala", "Ciliegino"],
                price: 8.0,
            },
            {
                id: 1504,
                name: "Toronto",
                ingredients: ["Pomodoro", "Bufala", "Sopressa", "Rucola"],
                price: 8.5,
            },
            {
                id: 1505,
                name: "San Paolo",
                ingredients: [
                    "Pomodoro",
                    "Bufala",
                    "Prosciutto alla brace",
                    "Ciliegino",
                    "Rucola",
                ],
                price: 9.5,
            },
            {
                id: 1506,
                name: "Alba",
                ingredients: [
                    "Pomodoro",
                    "Bufala",
                    "Porcini",
                    "Bresaola",
                    "Olio tartufato",
                ],
                price: 9.5,
            },
            {
                id: 1507,
                name: "Ribot",
                ingredients: [
                    "Pomodoro",
                    "Bufala",
                    "Sfilacci di cavallo",
                    "Olive",
                    "Pomodori secchi",
                ],
                price: 9.5,
            },
            {
                id: 1508,
                name: "San Siro",
                ingredients: [
                    "Pomodoro",
                    "Bufala",
                    "Sfilacci di cavallo",
                    "Scamorza",
                    "Ciliegino",
                ],
                price: 9.5,
            },
            {
                id: 1509,
                name: "Pinne Gialle",
                ingredients: [
                    "Pomodoro",
                    "Bufala",
                    "Tonno affumicato",
                    "Rucola",
                ],
                price: 9.5,
            },
            {
                id: 1510,
                name: "Mediterranea",
                ingredients: [
                    "Pomodoro",
                    "Bufala",
                    "Tonno affumicato",
                    "Pomodori secchi",
                    "Formaggio alle erbe",
                ],
                price: 9.5,
            },
            {
                id: 1511,
                name: "Friarielli",
                ingredients: ["Pomodoro", "Bufala", "Friarielli"],
                price: 8.5,
            },
            {
                id: 1512,
                name: "Taggiasche",
                ingredients: ["Pomodoro", "Bufala", "Olive taggiasche"],
                price: 8.5,
            },
        ],
    },
    {
        id: 16,
        category: "Pizze Bianche",
        products: [
            {
                id: 1601,
                name: "4 Formaggi",
                ingredients: ["Formaggi misti"],
                price: 7.0,
            },
            {
                id: 1602,
                name: "Asparagi",
                ingredients: ["Mozzarella", "Asparagi"],
                price: 6.0,
            },
            {
                id: 1603,
                name: "Porcini",
                ingredients: ["Mozzarella", "Funghi porcini"],
                price: 7.5,
            },
            {
                id: 1604,
                name: "Bucaniera",
                ingredients: [
                    "Mozzarella",
                    "Gorgonzola",
                    "Cipolla di tropea",
                    "Pancetta",
                ],
                price: 8.0,
            },
            { id: 1605, name: "Malibù", ingredients: [], price: 8.5 },
        ],
    },
    {
        id: 17,
        category: "Pizze Arrotolate",
        products: [
            {
                id: 1701,
                name: "Giorgia",
                ingredients: [
                    "Mozzarella",
                    "Brie",
                    "Pomodorini",
                    "Speck",
                    "Rucola",
                ],
                price: 8.5,
            },
            {
                id: 1702,
                name: "Susanna",
                ingredients: [
                    "Mozzarella",
                    "Zucchine",
                    "Stracchino",
                    "Mais",
                    "Prosciutto crudo",
                ],
                price: 8.5,
            },
            {
                id: 1703,
                name: "Atena",
                ingredients: [
                    "Mozzarella",
                    "Misto funghi",
                    "Feta greca",
                    "Pancetta",
                ],
                price: 8.5,
            },
        ],
    },
    {
        id: 18,
        category: "Insalatone",
        products: [
            {
                id: 1801,
                name: "Matrix",
                ingredients: [
                    "Insalata",
                    "Pomodoro",
                    "Tonno",
                    "Bufala",
                    "Gamberetti",
                    "Mais",
                ],
                price: 9.0,
            },
            {
                id: 1802,
                name: "Greca",
                ingredients: [
                    "Insalata",
                    "Pomodoro",
                    "Olive",
                    "Cetrioli",
                    "Feta greca",
                    "Cipolla",
                    "Tonno",
                ],
                price: 9.0,
            },
            {
                id: 1803,
                name: "Fresca",
                ingredients: [
                    "Insalata",
                    "Pomodoro",
                    "Tonno",
                    "Mozzarella",
                    "Frittatina",
                    "Carote",
                ],
                price: 9.0,
            },
        ],
    },
    {
        id: 19,
        category: "Snack",
        products: [
            {
                id: 1901,
                name: "Tostone",
                ingredients: ["Prosciutto", "Formaggio"],
                price: 4.5,
            },
            {
                id: 1902,
                name: "Tostone Farcito",
                ingredients: ["Prosciutto", "Formaggio", "Farcitura a scelta"],
                price: 5.5,
            },
            {
                id: 1903,
                name: "Focaccia Prosciutto Crudo",
                ingredients: ["Pane focaccia", "Prosciutto crudo"],
                price: 6.0,
            },
            {
                id: 1904,
                name: "Cheeseburger",
                ingredients: [
                    "Pane",
                    "Hamburger",
                    "Insalata",
                    "Pomodoro",
                    "Formaggio",
                ],
                price: 6.5,
            },
        ],
    },
];
